# branch.yaml
name: Branch Workflow
on:
  pull_request:
    branches_ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Ek işlemleri buraya ekleyebilirsiniz
