name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Write Commit SHAs to File
        run: |
          echo ${{ github.event.size }}"
      - name: Get commit SHA
        run: |
          ls -al
          whoami
          pwd
          echo "${{ github.event.before }}"
          git rev-parse HEAD
          git branch --contains HEAD | grep -q "test"
          echo $?

