name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit SHA
        run: |
          ls -al
          whoami
          pwd
          echo "${{ github.event.before }}"
          git branch --contains ${{ github.event.before }} | grep -q "test"
          echo $?

